[build]
root = "backend"
builder = "nixpacks"

[build.cmd]
cmd = "./mvnw clean package -DskipTests"

[deploy]
startCommand = "java -Dserver.port=$PORT -jar target/MoraPack-0.0.1-SNAPSHOT.jar"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10