name: Deploy Backend

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy usando SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            
            cd ~/MoraPack/MoraPack-Backend/backend
            
            
            git pull origin main
            
            
            chmod +x mvnw
            
            
            sudo pkill -9 -f java || true
            
            make set-up-db
            nohup make run > backend.log 2>&1 &
            
            echo "Despliegue Backend completado "